feat(jellyfish-api-core): add masternode clearMempool RPC
DeFiCh/jellyfishsdk pull request #1801
Opened 2022-10-13 08:36 UTC by helloscoopa

What this PR does / why we need it:
/kind feature

Which issue(s) does this PR fixes?:
Fixes part of https://github.com/JellyfishSDK/jellyfish/issues/48

- Implements `clearmempool` type for RPC.

2022-10-13 08:40 UTC, helloscoopa commented on packages/jellyfish-api-core/__tests__/category/masternode/clearMempool.test.ts
> +    expect(removedTxIds).toContain(createdTxId)
Here the `clearmempool` RPC returns duplicate transaction ids, for 1 transaction it returns two of the same ids. Not exactly sure of the reason for it. Thus for now just added a `toContain` assertion.

2022-10-14 05:54 UTC, fuxingloh requested changes

2022-10-14 05:54 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/masternode/clearMempool.test.ts
> +    expect(txIdsInMempoolBefore.length).toBe(1)
```suggestion
    expect(txIdsInMempoolBefore.length).toStrictEqual(1)
```

Equal instead due to number coercion

2022-10-14 05:54 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/masternode/clearMempool.test.ts
> +    expect(txIdsInMempoolAfter.length).toBe(0)
```suggestion
    expect(txIdsInMempoolAfter.length).toStrictEqual(0)
```

2022-10-14 07:59 UTC, fuxingloh approved these changes

2022-10-17 03:10 UTC, delphk approved these changes

2022-10-17 06:26 UTC, merged