feat(apps/whale-api): Add assetbreakdown endpoint
DeFiCh/jellyfishsdk pull request #1862
Opened 2022-11-16 17:32 UTC by helloscoopa

#### What this PR does / why we need it:

#### Additional comments?:
_Add assetbreakdown endpoint_

2022-11-16 17:51 UTC, helloscoopa commented on apps/whale-api/src/module.api/consortium.service.ts
> +      backed: '-1',
Backed amount is not fetched at the moment as it will be added in a future iteration.

2022-11-16 17:52 UTC, helloscoopa commented on apps/whale-api/src/module.api/consortium.service.ts
> +      ttl: 600 // 10 minutes
Using 10mins ttl for cache, not sure should I make it more or less here?

2022-11-18 03:32 UTC, helloscoopa commented
For the reference of reviewer: Regarding the proof of assets page, In design doc it says that one member might have more than one backing address per token, but from the DFC side, there is only one string field that contains such info, which is `backingId` under `v0/consortium/members` gov attributes. The `backingId` is a non validated field such that it can contain anything, so if this multi address per member per token is a valid thing, I suppose the `backingId` might contain for an example comma separated list of addresses. At the moment I'm returning the value as it is from the endpoint, still couldn't find more info on it.

<img width="772" alt="image" src="https://user-images.githubusercontent.com/26799723/202609914-03d5fd28-638b-4592-bddf-74350849093d.png">

2022-11-21 09:34 UTC, infinia-yzl requested changes
Consider writing tests for non-happy paths.

2022-11-21 09:34 UTC, infinia-yzl commented on apps/whale-api/src/module.api/consortium.controller.spec.ts
> +    await alice.generate(5)
I believe `.generate(1)` should suffice.

2022-11-21 09:34 UTC, infinia-yzl commented on apps/whale-api/src/module.api/consortium.controller.spec.ts
> +        { id: '01', name: 'alice', minted: '1.00000000', burnt: '0.00000000', backingAddresses: ['abc'], tokenId: idBTC },
`burned`

2022-11-24 09:44 UTC, infinia-yzl submitted a review, later dismissed
LGTM

2022-11-25 02:21 UTC, pierregee requested changes

2022-11-25 02:21 UTC, pierregee commented on apps/whale-api/src/module.api/consortium.service.ts
> +      assetBreakdownInfo.push({
From the design, both need`tokenDisplaySymbol` and `tokenSymbol` 
<img width="444" alt="image" src="https://user-images.githubusercontent.com/13292662/203886164-62cb59e2-4641-4ecc-a1d0-8da8dbb9d3da.png">
<img width="444" alt="image" src="https://user-images.githubusercontent.com/13292662/203886239-875d20ed-469f-440b-b25f-91da631e6337.png">

2022-11-25 09:46 UTC, pierregee approved these changes, later dismissed
LGTM!

2022-11-28 05:52 UTC, helloscoopa commented
Need to wait for this PR to be merged: https://github.com/JellyfishSDK/jellyfish/pull/1860

2022-11-29 08:16 UTC, infinia-yzl approved these changes, later dismissed
:shipit:

2022-11-29 14:24 UTC, cwkang1998 reviewed
Test is failing and require merge with main

2022-11-30 03:22 UTC, imkven reviewed
Leave some comments.

2022-11-30 03:22 UTC, imkven commented on apps/whale-api/src/module.api/consortium.controller.spec.ts
> +    const hash = await alice.rpc.masternode.setGov({ ATTRIBUTES })
```suggestion
  async function setGovAttr (attributes: object): Promise<void> {
    const hash = await alice.rpc.masternode.setGov({ ATTRIBUTES: attributes })
```

2022-11-30 03:22 UTC, imkven commented on packages/whale-api-client/__tests__/api/consortium.test.ts
> +    const hash = await alice.rpc.masternode.setGov({ ATTRIBUTES })
Same comment above.

2022-11-30 03:39 UTC, imkven approved these changes, later dismissed

2022-11-30 03:56 UTC, infinia-yzl submitted a review, later dismissed

2022-11-30 06:24 UTC, imkven approved these changes
LGTM

2022-11-30 06:29 UTC, infinia-yzl approved these changes
Hopefully the tests are no longer flaky.

2022-12-01 01:57 UTC, pierregee approved these changes

2022-12-01 13:24 UTC, fuxingloh approved these changes

2022-12-01 13:24 UTC, merged