feat(jellyfish-api-core): add verifyMessage and signMessageWithPrivKey RPCs
DeFiCh/jellyfishsdk pull request #1905
Opened 2022-12-05 12:03 UTC by shohamc1

#### What this PR does / why we need it:

Adds verifyMessage and signMessageWithPrivKey RPCs and tests.

#### Which issue(s) does this PR fixes?:

Fixes part of https://github.com/JellyfishSDK/jellyfish/issues/48

2023-01-11 10:01 UTC, shancht requested changes

2023-01-11 10:01 UTC, shancht commented on packages/jellyfish-api-core/__tests__/category/misc/signMessageWithPrivKey.test.ts
> +    const promise = client.misc.signMessageWithPrivKey('cRiRQ9cHmy5evDqNDdEV8f6zfbK6epi9Fpz4CRZsmLEmkwy54dWz', 'test')
What are your thoughts on the following lines instead for `line 32`?

```
    const privkey = await client.wallet.dumpPrivKey(await client.wallet.getNewAddress())
    const promise = client.misc.signMessageWithPrivKey(privkey, 'test')
```

2023-01-11 10:13 UTC, shohamc1 commented on packages/jellyfish-api-core/__tests__/category/misc/signMessageWithPrivKey.test.ts
> +    const promise = client.misc.signMessageWithPrivKey('cRiRQ9cHmy5evDqNDdEV8f6zfbK6epi9Fpz4CRZsmLEmkwy54dWz', 'test')
Seems like a much better way to do it, fixed in https://github.com/JellyfishSDK/jellyfish/pull/1905/commits/3ff9fe86f89fd768fb2cc6b6334c4aa1c1e1d02e

2023-01-12 04:30 UTC, shancht submitted a review, later dismissed
Looks good to me!

2023-01-12 06:17 UTC, marktanrj approved these changes, later dismissed
Looks good, left some comments

2023-01-12 06:17 UTC, marktanrj commented on packages/jellyfish-api-core/__tests__/category/misc/signMessageWithPrivKey.test.ts
> +    await container.waitForReady()
nitpick: `waitForReady()` is deprecated `start()` will automatically wait for ready

2023-01-12 06:17 UTC, marktanrj commented on packages/jellyfish-api-core/__tests__/category/misc/verifyMessage.test.ts
> +    await container.waitForReady()
Same for this

2023-01-12 06:27 UTC, marktanrj approved these changes
LGTM

2023-01-12 06:28 UTC, shancht approved these changes

2023-01-12 08:50 UTC, fuxingloh approved these changes

2023-01-12 08:50 UTC, merged