chore(packages/jellyfish-network): Add network port configuration
DeFiCh/jellyfishsdk pull request #1907
Opened 2022-12-06 08:27 UTC by helloscoopa

#### What this PR does / why we need it:
Adds port configurations to be used by https://github.com/JellyfishSDK/jellyfish/pull/1790

#### Additional comments?:
--

2022-12-06 13:38 UTC, fuxingloh requested changes

2022-12-06 13:38 UTC, fuxingloh commented on packages/jellyfish-network/src/Network.ts
> +  /** [HYDRA] */
```suggestion
```

2022-12-06 13:38 UTC, fuxingloh commented on packages/jellyfish-network/src/Network.ts
> +  */
```suggestion
 * Network specific DeFi configuration.
 * They can be found in DeFiCh/ain project in file chainparams.cpp, under base58Prefixes
 */
```

You need to revert these documentation indentation changes. It's not following the correct default expected indentations defined here https://jsdoc.app/about-getting-started.html

2022-12-07 06:55 UTC, infinia-yzl approved these changes

2022-12-07 07:21 UTC, fuxingloh approved these changes

2022-12-07 07:22 UTC, fuxingloh commented
> Adds port configurations to be used by #1790

You should describe why ports need to be declared.

2022-12-07 08:27 UTC, helloscoopa commented
> You should describe why ports need to be declared. Instead of just referencing another issue, this issue/pr should be standalone.

Updated 👍🏼

2022-12-07 08:50 UTC, merged