add signmessage() to wallet.ts
DeFiCh/jellyfishsdk pull request #1934
Opened 2022-12-16 05:41 UTC by shancht

**What this PR does / why we need it:** 
/kind feature

**Which issue(s) does this PR fixes?:** 
Adding `signMessage()` from [Issue#48](https://github.com/JellyfishSDK/jellyfish/issues/48)

This features allow users to sign an arbitrary message using the private key of an address. 
It requires wallet passphrase to be set with `walletpassphrase` call if the wallet is encrypted.

**Additional comments?:**
The primary purpose of `signMessage()` is to present a signature to showcase that the funds are in the control of the private key holder. The holder may also generate a signature with custom prefixes to showcase proof of authorisation.

Usage Example: [Here](https://bitcoin.stackexchange.com/a/3339/160)

2022-12-20 02:14 UTC, shancht commented
Hi, the DefiChain codebase (/rpcwallet.cpp) included a section to ensure that the wallet is not encrypted/locked. I'd like to seek clarification on how I could best write a syntax for this section in Jellyfish please:

```
    auto locked_chain = pwallet->chain().lock();
    LOCK2(pwallet->cs_wallet, locked_chain->mutex());

    EnsureWalletIsUnlocked(pwallet);
```

Thank you!

2022-12-21 06:07 UTC, shohamc1 commented
> Hi, the DefiChain codebase (/rpcwallet.cpp) included a section to ensure that the wallet is not encrypted/locked. I'd like to seek clarification on how I could best write a syntax for this section in Jellyfish please:
> 
> ```
>     auto locked_chain = pwallet->chain().lock();
>     LOCK2(pwallet->cs_wallet, locked_chain->mutex());
> 
>     EnsureWalletIsUnlocked(pwallet);
> ```
> 
> Thank you!

Not sure if this is a useful test, but you can set a wallet passphrase using `encryptwallet` and then use `walletlock` to lock the wallet. You can unlock the wallet later using `walletpassphrase`.

2022-12-22 09:42 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/wallet/signMessage.test.ts
> +    const promise = client.wallet.signMessage('mpLQjfK79b7CCV4VMJWEWAj5Mpx8Up5zxB', 'This is a test message')
```suggestion
    const address = await client.wallet.getNewAddress()
    const promise = client.wallet.signMessage(address, 'This is a test message')
```

This is how you create a new address within the Wallet and then use it for signing.

2023-01-09 05:24 UTC, fuxingloh approved these changes, later dismissed

2023-01-09 05:38 UTC, fuxingloh commented
LGTM,

@shohamc1 can you take a look at this and give it a review? Thanks!

2023-01-10 02:50 UTC, shohamc1 requested changes
Looks good minus this (the password is set using `encryptwallet`).

2023-01-10 02:50 UTC, shohamc1 commented on packages/jellyfish-api-core/src/category/wallet.ts
> +   * Requires wallet passphrase to be set with walletpassphrase call if wallet is encrypted.
```suggestion
   * Requires wallet to be unlocked for usage. Use `walletpassphrase` to unlock wallet.
```

2023-01-11 04:13 UTC, shohamc1 approved these changes, later dismissed

2023-01-11 05:46 UTC, fuxingloh approved these changes

2023-01-11 06:31 UTC, shohamc1 approved these changes

2023-01-11 07:12 UTC, merged