feat(misc): add deriveAddresses function
DeFiCh/jellyfishsdk pull request #1974
Opened 2023-01-16 03:02 UTC by DocteurPing

#### What this PR does / why we need it:

This PR adds the function deriveAddresses.

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2023-01-17 06:39 UTC, shohamc1 requested changes
It would be worth testing other output descriptors like `pkh` and `sh` which are also supported by the RPC.

2023-01-17 06:39 UTC, shohamc1 commented on packages/jellyfish-api-core/__tests__/category/misc/deriveAddresses.test.ts
> +    expect(await client.misc.deriveAddresses(descriptor)).toStrictEqual(address)
You should also check for the exact error thrown.

```suggestion
    const promise = client.misc.deriveAddresses(descriptor)).toStrictEqual(address)
    await expect(promise).rejects.toThrow(RpcApiError)
    await expect(promise).rejects.toMatchObject({
      payload: {
        code: -5,
        message: '<err message>',
        method: 'deriveaddresses'
      }
    })
```

2023-01-17 06:39 UTC, shohamc1 commented on packages/jellyfish-api-core/__tests__/category/misc/deriveAddresses.test.ts
> +  it('should raise an error if range is inferior to 0', async () => {
```suggestion
  it('should raise an error if range is less than 0', async () => {
```

2023-01-17 06:39 UTC, shohamc1 commented on packages/jellyfish-api-core/__tests__/category/misc/deriveAddresses.test.ts
> +  it('should raise an error if end of range is inferior to beginning', async () => {
```suggestion
  it('should raise an error if end of range is smaller than the beginning', async () => {
```

2023-01-18 03:40 UTC, shohamc1 requested changes

2023-01-18 03:40 UTC, shohamc1 commented on packages/jellyfish-api-core/__tests__/category/misc/deriveAddresses.test.ts
> +    expect(await client.misc.deriveAddresses(descriptor, [1, 2])).toStrictEqual(address)
```suggestion
    await expect(client.misc.deriveAddresses(descriptor, [1, 2])).toStrictEqual(address)
```

2023-01-18 06:35 UTC, shohamc1 approved these changes

2023-01-19 06:51 UTC, fuxingloh approved these changes

2023-01-19 07:40 UTC, merged