feat(misc): add createMultiSig function
DeFiCh/jellyfishsdk pull request #1977
Opened 2023-01-16 09:38 UTC by DocteurPing

#### What this PR does / why we need it:

This PR adds the function createMultiSig.

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2023-01-17 06:54 UTC, shohamc1 requested changes
Missing a test case for "Unknown address type" (when an invalid `addressType` is passed).

2023-01-17 06:54 UTC, shohamc1 commented on packages/jellyfish-api-core/__tests__/category/misc/createMultiSig.test.ts
> +    await expect(client.misc.createMultiSig(2, keys, 'legacy')).rejects.toThrow(RpcApiError)
Test for the error thrown: https://github.com/JellyfishSDK/jellyfish/pull/1974#discussion_r1071791232

2023-01-17 06:54 UTC, shohamc1 commented on packages/jellyfish-api-core/__tests__/category/misc/createMultiSig.test.ts
> +  it('should throw error if n is inferior to 0', async () => {
```suggestion
  it('should throw error if n < 0', async () => {
```

2023-01-17 06:54 UTC, shohamc1 commented on packages/jellyfish-api-core/src/category/misc.ts
> +  async createMultiSig (nrequired: number, keys: string[], addressType: string = 'legacy'): Promise<MultiSigAddress> {
```suggestion
  async createMultiSig (nRequired: number, keys: string[], addressType: string = 'legacy'): Promise<MultiSigAddress> {
```

2023-01-17 09:47 UTC, shohamc1 submitted a review, later dismissed
LGTM minus nitpick.

2023-01-17 09:47 UTC, shohamc1 commented on packages/jellyfish-api-core/__tests__/category/misc/createMultiSig.test.ts
> +  it('should throw error if n < 0', async () => {
```suggestion
  it('should throw error if nRequired < 0', async () => {
```

2023-01-18 03:41 UTC, shohamc1 approved these changes, later dismissed

2023-01-19 06:51 UTC, fuxingloh requested changes

2023-01-19 06:51 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/misc/createMultiSig.test.ts
> +  it('should create multi signature address', async () => {
This is the bare minimum; we need more scenarios.

2023-01-25 05:01 UTC, fuxingloh commented
Test are not running, conflicts

2023-01-26 13:09 UTC, fuxingloh requested changes

2023-01-26 13:09 UTC, fuxingloh commented on packages/jellyfish-api-core/src/category/misc.ts
> +   * @return Promise<MultiSigAddress> The signature of the message encoded in base 64
```suggestion
   * @param {number} nRequired The number of required signatures out of the n keys.
   * @param {string[]} keys array of hex-encoded public keys.
   * @param {string} [addressType='legacy'] the address type to use. Options are 'legacy', 'p2sh-segwit', and 'bech32'.
   * @return Promise<MultiSigAddress> The signature of the message encoded in base 64
```

2023-01-26 13:09 UTC, fuxingloh commented on packages/jellyfish-api-core/src/category/misc.ts
> +  async createMultiSig (nRequired: number, keys: string[], addressType: string = 'legacy'): Promise<MultiSigAddress> {
Since `addressType` is an enum, use/introduce an enum type?

2023-01-26 13:09 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/misc/createMultiSig.test.ts
> +    let key0 = (await testing.rpc.wallet.getAddressInfo(await testing.rpc.wallet.getNewAddress('', wallet.AddressType.LEGACY))).pubkey
Seems like this is a common code section, maybe you create top-level function for this.

2023-01-26 13:09 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/misc/createMultiSig.test.ts
> +    key0 = ECDH.convertKey(key0, 'secp256k1', 'hex', 'hex', 'uncompressed').toString()
Why is the first key converted but not the 2 and 3?

2023-01-27 02:06 UTC, DocteurPing commented on packages/jellyfish-api-core/__tests__/category/misc/createMultiSig.test.ts
> +    key0 = ECDH.convertKey(key0, 'secp256k1', 'hex', 'hex', 'uncompressed').toString()
We only have to convert one key to be able to retrieve the address so i decided to not convert the other keys to save ressources.

2023-02-01 04:36 UTC, fuxingloh commented on packages/jellyfish-api-core/src/category/misc.ts
> +import { wallet } from '@defichain/jellyfish-api-core'
```suggestion
import { wallet } from '../???'
```

Best use relative path for internal linking.

2023-02-01 04:37 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/misc/createMultiSig.test.ts
> +    const legacyAddr = (await client.misc.createMultiSig(2, keys, wallet.AddressType.LEGACY)).address
```suggestion
    const { address } = await client.misc.createMultiSig(2, keys, wallet.AddressType.LEGACY)
```

Alternatively so you about parenthesis, which can be harder to read/review.

2025-01-06 12:46 UTC, closed without merging